### PR TITLE
Update project name in XML file

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
Changed the project name in the XML file from "org.eclipse.4diac.forte" to "4diac-forte".

### CODE REVIEW

**Comment by azoitl** [comment]
Personally I would like to keep the old project name. @MartinMelikMerkumians @moniwe @bwiesmayr what do you think?

**Comment by franz-hoepfinger-4diac** [comment]
> Personally I would like to keep the old project name.

in eclipse i experienced Problems when Folder Name and Project Name is not same.

**Comment by azoitl** [comment]
> > Personally I would like to keep the old project name.
> 
> in eclipse i experienced Problems when Folder Name and Project Name is not same.

I have several examples on my machine which prove the opposite. So your problems need to come from something else.

**Comment by moniwe** [comment]
in my Eclipse everything seems to be fine. Which problems did you have?

**Comment by diplfranzhoepfinger** [comment]
> in my Eclipse everything seems to be fine. Which problems did you have?

at espressif eclipse plugin the hex files was lost. 

because the build script took the wrong one (path vs. Project name). 

must look after where i documented this issue.

**Comment by moniwe** [comment]
i guess most 4diac contributor/commiter do not use this plugin? At least this explains why we do not have this problem. For Java developers this difference in project name and folder name is quite common i think, at least i am used to it from where i work. Changeing it would mean to have a different naming for IDE and RTE within Eclipse wouldn't it? Maybe your build script could change the folder?

**Comment by diplfranzhoepfinger** [comment]
yes, this turns out to be a pure "comfort" issue now. not more. 

i will make 2 Screenshots how it looks in Eclipse.

**Comment by diplfranzhoepfinger** [comment]
it looks like this with non-Changed Name, 

checkout from [https://github.com/eclipse-4diac](https://github.com/eclipse-4diac)

and imported:



my Proposal leads to this: 



so just cosmetics now.

**Comment by azoitl** [comment]
You can also rename your directory to your needs. I for example still have the old name `org.eclipse.4diac.forte` for my 4diac FORTE repo. The reason mainly is that I just changed the links for origin and upstream in my git config.

**Comment by MartinMelikMerkumians** [comment]
IMHO, keeping `org.eclipse.4diac.forte` is preferable for me, as it also points to the project as a whole.

**Review by MartinMelikMerkumians — COMMENTED** [review]
I would keep the original, as it points to eclipse and the project as a whole

**Comment by MartinMelikMerkumians** [comment]
Thanks for your PR, but we keep the original name

**Pull request closed without merging**
