### PR TITLE
Fix VisualStudio 2022 compilation errors.

### PR DESCRIPTION
**Pull request by melekhove**
VS 2022 compiler seems to be a bit more strict in some aspects.

### CODE REVIEW

**Review by azoitl — COMMENTED** [review]
As far as I understood @mx990 we could remove the whole initializer here as C++ would anyhow automatically initialize all values with 0 or nullptrs. Am I right @mx990?

**Comment by melekhove** [comment]
I'm afraid, it is not that clear. Initialization syntax & semantics differ across time, c++ standard and compilers.
In the following [document](https://en.cppreference.com/w/cpp/language/initialization) you can see a lot of clauses like (until/since C++11/C++20 ) :-)
Taking into account different compilers (gcc/clang/lc etc)I'd prefer to be on the safe side & initialize struct on the stack explicitly.

**Comment by mx990** [comment]
> As far as I understood @mx990 we could remove the whole initializer here as C++ would anyhow automatically initialize all values with 0 or nullptrs. Am I right @mx990?

Yes, I would suggest the following:
```c++
SFBInterfaceSpec interfaceSpec{};
```

> I'm afraid, it is not that clear. Initialization syntax & semantics differ across time, c++ standard and compilers. In the following [document](https://en.cppreference.com/w/cpp/language/initialization) you can see a lot of clauses like (until/since C++11/C++20 ) :-) Taking into account different compilers (gcc/clang/lc etc)I'd prefer to be on the safe side & initialize struct on the stack explicitly.

The semantics regarding initialization as defined in the C++ standard have indeed been updated several times, mostly to account for new features added to the language. This makes the article regarding initialization somewhat hard to read.

I would still like to point you to https://en.cppreference.com/w/cpp/language/zero_initialization, particularly clause (2) and also the example code at the end. As you can see, little has changed regarding that topic. Please note that we are also only targeting C++ 17 and above.

As for the behavior of different compilers, I believe it is impossible to anticipate the quirks of all the compilers out there. Being extra verbose may also lead to problems sometimes, as clearly evidenced by this PR. Aside from that, if you have any concrete information of a compiler misbehaving here, please let us know, so we can take appropriate action.

**Comment by melekhove** [comment]
Ok, done.

**Review by mx990 — APPROVED** [review]

**Review by azoitl — APPROVED** [review]

**Comment by azoitl** [comment]
@melekhove thx for finding this problem and the updated fix.

**Pull request merged**
