### PR TITLE
Update compiler flags to remove "no deprecated warnig" declarations.

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
Changed compiler flags to **exclude** "deprecated declarations" for C and C++ files in multiple toolchain configurations.

### CODE REVIEW

**Comment by ernstblechaPT** [comment]
Could you give an example of the deprecated-warnings you receive for the esp32 platform? I'd rather not suppress those warnings as they are meant as a call to action for everyone using deprecated features.

**Comment by cochicde** [comment]
> Could you give an example of the deprecated-warnings you receive for the esp32 platform? I'd rather not suppress those warnings as they are meant as a call to action for everyone using deprecated features.

I agree. What's the motivation to remove warnings? I think is better to remove the deprecated things that it's complaining about

**Comment by mx990** [comment]
I believe the warnings were previously suppressed by `-Wno-deprecated-declarations` and removing the option re-enables them. From the gcc manual:
> -Wno-deprecated-declarations
    Do not warn about uses of functions, variables, and types marked as deprecated by using the deprecated attribute.

**Review by ernstblechaPT — APPROVED** [review]
@mx990 you are right, the change removes the flag. I completly misread the title and the message of the pull request

Maybe the title and the message of the pull request could be improved before merging.

**Comment by franz-hoepfinger-4diac** [comment]
> Could you give an example of the deprecated-warnings you receive for the esp32 platform? I'd rather not suppress those warnings as they are meant as a call to action for everyone using deprecated features.

YES, i REMOVED the ` -Wno-deprecated-declarations` Option. 

so Deprecated Code will be SHOWN

**Comment by franz-hoepfinger-4diac** [comment]
> Maybe the title and the message of the pull request could be improved before merging.

yes, this comes from using Chat GPT for generating this, sometimes this saves time, sometimes it leads to misunderstand. 
i updated it to be cleaner.

**Review by ernstblechaPT — APPROVED** [review]

**Review by azoitl — APPROVED** [review]

**Pull request merged**
