### PR TITLE
Update to Basic FB, added new data types and algorithms for event execution.

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
Update to Basic FB, added new data types and algorithms for event execution.

- Changed function block to Basic FB
- Added new data types for variables
- Implemented algorithms for event execution

### CODE REVIEW

**Comment by franz-hoepfinger-4diac** [comment]
https://github.com/eclipse-4diac/4diac-ide/pull/277

**Comment by franz-hoepfinger-4diac** [comment]
https://chat.eclipse.org/#/room/!yVjgkwgBPbjMVDziCd:matrix.eclipse.org/$ABCEiLWvslBAQP6WRujC3wQ7tMMu0RZwme7lUbNMaus?via=matrix.eclipse.org&via=matrix.org

**Comment by azoitl** [comment]
what is the need to change working FB's code. Especially to less efficient and with more memory requirements?

**Comment by diplfranzhoepfinger** [comment]
ah, Basic FB needs more memory right ? 

OK, this i overlooked ...

**Pull request closed without merging**
