### PR TITLE
compile only C library if chosen

### PR DESCRIPTION
**Pull request by cochicde**

### CODE REVIEW

**Comment by diplfranzhoepfinger** [comment]
Interesting ! 

i want to test it ...

**Comment by cochicde** [comment]
> Interesting ! 
> 
> i want to test it ...

that'd be great. Thanks!

**Comment by cochicde** [comment]
@diplfranzhoepfinger any updates on this?

**Comment by franz-hoepfinger-4diac** [comment]
WORKING !

**Review by azoitl — APPROVED** [review]

**Pull request merged**
