### PR TITLE
add distance module with RangeBasedPulse functionality.

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
see also 
https://github.com/eclipse-4diac/4diac-ide/pull/644
https://github.com/eclipse-4diac/4diac-ide/pull/760

### CODE REVIEW

**Comment by MandKastner** [comment]
Note: this will conflict with #273 either add the event types manually to `scmFBInterfaceSpec` or reexport the FB with the updated exporter

**Comment by diplfranzhoepfinger** [comment]
I preffer re-exporting. 

which 4diac IDE Version to use for it ? 

thanks!

**Comment by MandKastner** [comment]
I think nightly and milestone build of 4diac IDE should now contain the adapted exporter

**Comment by diplfranzhoepfinger** [comment]
will make a new Export today.

**Review by azoitl — APPROVED** [review]

**Pull request merged**
