### PR TITLE
Replaced CIEC_STRING with std::string in SManagementCMD

### PR DESCRIPTION
**Pull request by azoitl**
SManagementCMD stillused a CIEC_STRING for mAdditionalParams. With this clean-up this is finally migrated to std::string.

### CODE REVIEW

**Review by MartinMelikMerkumians — COMMENTED** [review]
Can you please check on resource.cpp lines 293, 306, and  316 if those conditions still make sense? Sorry, I cannot comment on them directly, as they have not been changed, but checking if the returned string fits into a CIEC_STRING seems to make no sense if a std::string is sed to save the value.

**Comment by azoitl** [comment]
@MartinMelikMerkumians thx for noting. Yes this ifs where not needed in that form anymore. I also did a bit of clean-up around that.

**Comment by azoitl** [comment]
Thx for noting. Yes this ifs can be simplified. Did also some further clean-ups.

**Review by MartinMelikMerkumians — APPROVED** [review]

**Comment by MartinMelikMerkumians** [comment]
Thanks, looks good now

**Pull request merged**
