### PR TITLE
Add Timer FBs

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
These Timer FBs rely on E_DELAY, so no need for call them cyclically.

### CODE REVIEW

**Comment by azoitl** [comment]
@franz-hoepfinger-4diac  As you changed the E_TP block I think you need to regenerate its source or?

**Comment by azoitl** [comment]
> @franz-hoepfinger-4diac As you changed the E_TP block I think you need to regenerate its source or?

@franz-hoepfinger-4diac ping

**Comment by franz-hoepfinger-4diac** [comment]
@azoitl pls check. 
should be good now.

**Review by azoitl — CHANGES_REQUESTED** [review]
For the new FBs the copyright headers seem to be wrong. These are new FBs done be you @franz-hoepfinger-4diac and done last year. So I don't see why there should be a TU Wien and the year 2012 in copy right header.

**Comment by diplfranzhoepfinger** [comment]
> For the new FBs the copyright headers seem to be wrong. These are new FBs done be you @franz-hoepfinger-4diac and done last year. So I don't see why there should be a TU Wien and the year 2012 in copy right header.

oh ... no ...

**Comment by diplfranzhoepfinger** [comment]
see now please @azoitl

**Review by azoitl — APPROVED** [review]

**Comment by azoitl** [comment]
> see now please @azoitl

Thx for fixing.

**Pull request merged**
