### PR TITLE
Add ASSEMBLE_XX_FROM_BOOLS fct files under utils

### PR DESCRIPTION
**Pull request by MoritzO02**
Created a directory under utils named "assembling" and added four functions. In total eight files.

for issue eclipse-4diac/4diac-ide#221

### CODE REVIEW

**Review by azoitl — CHANGES_REQUESTED** [review]
Can you please fix the copyright headers. In that form they are not acceptable.

**Comment by MoritzO02** [comment]
> Can you please fix the copyright headers. In that form they are not acceptable.

Have the headers like this with one *?
image

So it is also wrong in this file?
image

**Comment by azoitl** [comment]
@MoritzO02 both I fine. I just had a second look at your PR. The reason I missunderstood is that you made a PR with 6 commits. When I get PRs like that I assume that each commit is in itself self contained and should be preserved. Therefore I review each commit individually. This makes reviewing commits easier for me. So for the future I kindly ask you to support me making reviews for your PRs easier. You can do this by presquashing your commits on your side and rebasing the result on top of develop. This allows you also to give the final commit message and I don't have to generate one when squashing the commits on my side here in github.

**Comment by franz-hoepfinger-4diac** [comment]
@azoitl now squashed.

**Review by franz-hoepfinger-4diac — APPROVED** [review]

**Review by azoitl — APPROVED** [review]

**Pull request merged**
