### PR TITLE
Make Scripts for Windows build

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
Make Scripts for Windows build

### CODE REVIEW

**Comment by azoitl** [comment]
Do we really need that?

**Comment by diplfranzhoepfinger** [comment]
> Do we really need that?

Without that we must work with the buggy CMAKE GUI. I hate it so much. 
If You have alternatives I am very open. 
But it should be Command line based not Clickie-Clickie based.

**Comment by azoitl** [comment]
> > Do we really need that?
> 
> Without that we must work with the buggy CMAKE GUI. I hate it so much. If You have alternatives I am very open. But it should be Command line based not Clickie-Clickie based.

I know that you are not happy with the CMake GUI. Which as I told you, I don't understand at all. But I guess this is something we both will never come on par. 

That aside, the question was mostly targeted for @jwalt. Because your shell script is just duplicating what is now better available in fbe.

**Comment by jwalt** [comment]
I agree with @azoitl we should start transitioning to 4diac-fbe instead. Technically it is pretty stable, but we probably will need to update/add docs for the new preferred way of building forte. FBE has configs for windows in the `configurations/tests` subdir

**Comment by diplfranzhoepfinger** [comment]
> I know that you are not happy with the CMake GUI. Which as I told you, I don't understand at all. 

take only the fact that CMAKE GUI set the Loglevel back to NONE always, and nobody can solve it since 2 years .

this makes me anxious and unhappy, because such a tool is unreliable. What else can be set without manual intervention ? in a Textfile i can set things on and off, and can control this safely with git.

**Comment by diplfranzhoepfinger** [comment]
> I agree with @azoitl we should start transitioning to 4diac-fbe instead.

yes, agree. 

>  Technically it is pretty stable, but we probably will need to update/add docs for the new preferred way of building forte. FBE has configs for windows in the `configurations/tests` subdir

4diac-fbe Build fails in release, and not even starts in develop. 

the build described in [https://eclipse.dev/4diac/en_help.php?helppage=html/installation/install.html#ownFORTE](https://eclipse.dev/4diac/en_help.php?helppage=html/installation/install.html#ownFORTE) runs. 

so, keep rocking, i would love to see 4diac-fbe working first time.

**Comment by azoitl** [comment]
I'm regularly using FBE builds, I can not confirm your observation.

**Comment by diplfranzhoepfinger** [comment]
> I'm regularly using FBE builds, I can not confirm your observation.

this is clear. you developed the System, you know how to operate it. 

i am new, i did it exactly according to the Manual on a fresh clone, and it not works in multiple ways. I ask for Help. Logs are provided in big variety.

**Comment by azoitl** [comment]
> > I'm regularly using FBE builds, I can not confirm your observation.
> 
> this is clear. you developed the System, you know how to operate it. 

No I didn't I'm just a user like you.

> 
> i am new, i did it exactly according to the Manual on a fresh clone, and it not works in multiple ways. I ask for Help. Logs are provided in big variety.

I rechecked my setup. I'm using fbe release branch. However I'm providing the configuration to build to the configure.sh script. As I don't want to build all. Please have a look in the configurations directory for sample configurations you can use for your builds as starters. The default examples enable a lot. This is maybe not what you want.

**Comment by diplfranzhoepfinger** [comment]
i think continue this Discussion in 

*   [https://github.com/eclipse-4diac/4diac-fbe](https://github.com/eclipse-4diac/4diac-fbe) 
*   eclipse-4diac/4diac-fbe#13

**Comment by MartinMelikMerkumians** [comment]
> take only the fact that CMAKE GUI set the Loglevel back to NONE always, and nobody can solve it since 2 years .

I never had that issue in all the years using it (assuming you mean FORTE log level). You sure, that not something in the CMake configuration is doing it, like setting the build type to release?

Also, I am not aware of any bug report about this behavior. Correct my if I am wrong, but if there is no issue, nobody will investigate.

**Pull request closed without merging**
