### PR TITLE
Update readme.txt

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
The Modbus client can be used for reading as well as writing values from/to a Modbus server.

this might mislead new persons a lot otherwise.

### CODE REVIEW

**Comment by azoitl** [comment]
@kumajaya and @franz-hoepfinger-4diac  shouldn't remove this file as a whole and migrate it to our [modbus documentation](https://github.com/eclipse-4diac/4diac-documentation/blob/main/src/communication/modbus.adoc) so that all documentation is in one place?

**Comment by diplfranzhoepfinger** [comment]
> @kumajaya and @franz-hoepfinger-4diac shouldn't remove this file as a whole and migrate it to our [modbus documentation](https://github.com/eclipse-4diac/4diac-documentation/blob/main/src/communication/modbus.adoc) so that all documentation is in one place?

I wanted to do this anyhow today. 

The Modbus Documentation is horrible outdated; so needs massive rework.

**Comment by diplfranzhoepfinger** [comment]
> > @kumajaya and @franz-hoepfinger-4diac shouldn't remove this file as a whole and migrate it to our [modbus documentation](https://github.com/eclipse-4diac/4diac-documentation/blob/main/src/communication/modbus.adoc) so that all documentation is in one place?
> 
> I wanted to do this anyhow today.
> 
> The Modbus Documentation is horrible outdated; so needs massive rework.

I see it is partially updated already. 
How can it come to the 4diac Website? There the Information is still old!

**Comment by azoitl** [comment]
> > > @kumajaya and @franz-hoepfinger-4diac shouldn't remove this file as a whole and migrate it to our [modbus documentation](https://github.com/eclipse-4diac/4diac-documentation/blob/main/src/communication/modbus.adoc) so that all documentation is in one place?
> > 
> > 
> > I wanted to do this anyhow today.
> > The Modbus Documentation is horrible outdated; so needs massive rework.
> 
> I see it is partially updated already. How can it come to the 4diac Website? There the Information is still old!

We are in the making of a new web-page which will utilize the new documentation. Therefore I don't want to spend to much time on the old one. What we could do is to cahnge the Documentation link to https://github.com/eclipse-4diac/4diac-documentation/blob/main/src/intro/iec61499.adoc 

What do you think?

**Comment by bwiesmayr** [comment]
> > > > @kumajaya and @franz-hoepfinger-4diac shouldn't remove this file as a whole and migrate it to our [modbus documentation](https://github.com/eclipse-4diac/4diac-documentation/blob/main/src/communication/modbus.adoc) so that all documentation is in one place?
> > > 
> > > 
> > > I wanted to do this anyhow today.
> > > The Modbus Documentation is horrible outdated; so needs massive rework.
> > 
> > 
> > I see it is partially updated already. How can it come to the 4diac Website? There the Information is still old!
> 
> We are in the making of a new web-page which will utilize the new documentation. Therefore I don't want to spend to much time on the old one. What we could do is to cahnge the Documentation link to https://github.com/eclipse-4diac/4diac-documentation/blob/main/src/intro/iec61499.adoc
> 
> What do you think?

That is an absolutely excellent idea, I totally support this change. It is currently a bit frustrating to update the documentation when it cannot be mirrored to the website - I think this change not only helps new users get more updated information, but also motivates to edit the documentation.

**Comment by franz-hoepfinger-4diac** [comment]
> @kumajaya and @franz-hoepfinger-4diac shouldn't remove this file as a whole 

DONE

**Comment by azoitl** [comment]
> > > > > @kumajaya and @franz-hoepfinger-4diac shouldn't remove this file as a whole and migrate it to our [modbus documentation](https://github.com/eclipse-4diac/4diac-documentation/blob/main/src/communication/modbus.adoc) so that all documentation is in one place?
> > > > 
> > > > 
> > > > I wanted to do this anyhow today.
> > > > The Modbus Documentation is horrible outdated; so needs massive rework.
> > > 
> > > 
> > > I see it is partially updated already. How can it come to the 4diac Website? There the Information is still old!
> > 
> > 
> > We are in the making of a new web-page which will utilize the new documentation. Therefore I don't want to spend to much time on the old one. What we could do is to cahnge the Documentation link to https://github.com/eclipse-4diac/4diac-documentation/blob/main/src/intro/iec61499.adoc
> > What do you think?
> 
> That is an absolutely excellent idea, I totally support this change. It is currently a bit frustrating to update the documentation when it cannot be mirrored to the website - I think this change not only helps new users get more updated information, but also motivates to edit the documentation.

Done!

**Comment by diplfranzhoepfinger** [comment]
@azoitl this is good now, 

if anybody click to "Documentation" he comes to the new Doc. 

good. 

but the old Docs are still available via Google. This will be solved once the new Webpage is online right ?

**Comment by azoitl** [comment]
@diplfranzhoepfinger I kept the old docs so that I can still look on the implementation and some styling when we finally roll out the new web-page.

**Comment by diplfranzhoepfinger** [comment]
yes, very clear for me ... 

my Question was how this will behave _after_ the rollout:

[https://eclipse.dev/4diac/en_help.php?helppage=html/communication/modbus.html](https://eclipse.dev/4diac/en_help.php?helppage=html/communication/modbus.html)

this link can be found in Googe, typing _4diac modbus_ and this should not point to old docs _forever._

After the Rollout it should point to the new docs _or_ a 404 should be generated, so Google will remove this from the Search index.

**Comment by azoitl** [comment]
ah that you mean. I know how to fix that.

**Pull request merged**
